### ISSUE TITLE
darabos_christian not showing up

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/website#1035]
I just checked the website and this person isn't showing on the website. Did I do something incorrect?

**Comment by weaverbel** [comment]
No entry for him in https://github.com/swcarpentry/website/tree/gh-pages/files/people - that might be why? @sheraaron

**Comment by weaverbel** [comment]
Is this fixed @sheraaron

**Comment by weaverbel** [comment]
Did we get anywhere with this? @sheraaron

**Comment by weaverbel** [comment]
Looks like he is listed. Closing.
