### ISSUE TITLE
Wrong youtube setup video loads in Firefox 

### ISSUE THREAD

**Issue by danaikorre** [swcarpentry/website#1233]
I tried to create a scw workshop for Python but noticed that in the setup instructions, in the Python field, it loads the instalation youtube video for R instead of Python. I checked on other browsers and noticed that it only happens on Firefox.

**Comment by maneesha** [comment]
Thanks for sharing this @dsmanufacturing 
Can you share where you see the problematic link?

**Comment by maneesha** [comment]
Checking in @dsmanufacturing

**Comment by datascimanufacturing** [comment]
Hi, Sorry I missed your first reply. The issues was resolved a few days later. I am not sure if someone fixed it or if it was an issue on my end.
