### ISSUE TITLE
Images and info on landing page

### ISSUE THREAD

**Issue by martinosorb** [swcarpentry/website#1238]
_I'm trying to start opening a few issues as part of a review of the website that I would like to have with the SWC Lesson Programme Governance Committee. The opinion here is my own but I will try to discuss these topics with the rest of the @swcarpentry/governance-committee ._

My first impression was that the three images corresponding to "our workshops", "our lessons" and "get involved" are outdated and could benefit from a new more professional looking choice. They have been last updated 8 years ago. We could use some stock images, for example from Unsplash, which has a lot of free-to-use material, or we could ask the community to provide good-quality pictures of CarpentryCon and workshops.

Additionally, there is no "what is software carpentry" information anywhere prominent on the website. We could add a fourth image linking to the "about" page, or a short text.

**Comment by maneesha** [comment]
@martinosorb Thanks so much for raising these issues.  I'm putting the same response in each issue:

You are right.  We recognize there is a lot of content on the website that needs review.  The Carpentries is currently in the middle of a large project to re-organize all our websites (The Carpentries and the three lesson programs).  We will be considering issues like this in that context, so I am closing them here.
