### ISSUE TITLE
What should we do with the blog and comments?

### ISSUE THREAD

**Issue by martinosorb** [swcarpentry/website#1239]
_I'm trying to start opening a few issues as part of a review of the website that I would like to have with the SWC Lesson Programme Governance Committee. The opinion here is my own but I will try to discuss these topics with the rest of the @swcarpentry/governance-committee ._

The **blog** has not been updated since 2018 and I suspect it should be considered superseded by the carpentries.org blog.
It think it would be nice to either
- archive it, making it clear that it is there for historical purposes, and remove  the 'recent posts' part in the homepage, avoiding the feeling that the site is abandoned
- revamp it, asking community members to propose topics  such as ideas on teaching
I personally lean on the first option, to be honest.

The **comments** sections should, in my opinion, be removed. Without a constantly updated blog, they make little sense. Moreover, some people have been trying to use them to ask for information (see the comments section at the bottom of the homepage). So they should be monitored if kept.

**Comment by maneesha** [comment]
@martinosorb Thanks so much for raising these issues.  I'm putting the same response in each issue:

You are right.  We recognize there is a lot of content on the website that needs review.  The Carpentries is currently in the middle of a large project to re-organize all our websites (The Carpentries and the three lesson programs).  We will be considering issues like this in that context, so I am closing them here.
