### ISSUE TITLE
Graphs in the About page

### ISSUE THREAD

**Issue by martinosorb** [swcarpentry/website#1240]
_I'm trying to start opening a few issues as part of a review of the website that I would like to have with the SWC Lesson Programme Governance Committee. The opinion here is my own but I will try to discuss these topics with the rest of the @swcarpentry/governance-committee ._

The [about page](https://software-carpentry.org/about/) contains some graphs showing the expansion of the Carpentries community. I noticed that they are outdated (last updated 2018)  and their axes are hard to read. What shall we do about them?

Edit: the same graphs are in the "pitching a workshop" page and similar ones are in the "history" page.

**Comment by maneesha** [comment]
@martinosorb Thanks so much for raising these issues.  I'm putting the same response in each issue:

You are right.  We recognize there is a lot of content on the website that needs review.  The Carpentries is currently in the middle of a large project to re-organize all our websites (The Carpentries and the three lesson programs).  We will be considering issues like this in that context, so I am closing them here.
