### ISSUE TITLE
Pages in the menu, and role w.r.t carpentries.org

### ISSUE THREAD

**Issue by martinosorb** [swcarpentry/website#1241]
_I'm trying to start opening a few issues as part of a review of the website that I would like to have with the SWC Lesson Programme Governance Committee. The opinion here is my own but I will try to discuss these topics with the rest of the @swcarpentry/governance-committee ._

This is a bit of a 'misc' issue intended for discussion. As a user of the website, who had not much explored it before, I feel there are a lot of pages in the menus. Some of them redirect to carpentries.org, others don't, and it's hard to predict which ones for someone who is exploring the website. Some pages should be checked to see if they require updates ("reading materials", "software carpentry foundation", ...).

I think solving this should perhaps be preceded by a discussion on what we want from the website, i.e. what should its role be in relation to the carpentries.org website.

**Comment by maneesha** [comment]
@martinosorb Thanks so much for raising these issues.  I'm putting the same response in each issue:

You are right.  We recognize there is a lot of content on the website that needs review.  The Carpentries is currently in the middle of a large project to re-organize all our websites (The Carpentries and the three lesson programs).  We will be considering issues like this in that context, so I am closing them here.
