### ISSUE TITLE
Check credentials for lesson feed 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website#1243]
@zkamvar  @tobyhodges 
The script to build the lesson dashboard failed.  Looks like it is due to a credential error.  Was this due to changes either of you have been making? 

https://github.com/swcarpentry/website/actions/runs/4980066415/jobs/8914441707

**Comment by zkamvar** [comment]
This was a credentials rotation error. GitHub was on the struggle bus on Friday when I was trying to rotate the credentials, so I couldn't get to them in time. They all expired today before I woke up. 

I just rotated the credentials and rerun the job.
