### ISSUE TITLE
Link to lesson template 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website#1247]
On the [lessons page](https://software-carpentry.org/lessons/), we link to the [Carpentries styles repo](https://github.com/carpentries/styles) for the lesson template. What should this be changed to?

**Comment by zkamvar** [comment]
If it's talking about a template to create new lessons, it should point to https://github.com/carpentries/workbench-template-md/#readme (for Markdown lessons) and https://github.com/carpentries/workbench-template-rmd/#readme (for R Markdown lessons).

That being said, we do not create new official lessons before they are taught, so I'm wondering if those sentences really need to be there given that the "Contributing" section talks about The Workbench infrastructure.

**Comment by maneesha** [comment]
Happy to have this be whatever you think is best.  Feel free to put in a PR or share info here and I'll do the PR.
