### ISSUE TITLE
Remove "Previous Material" page 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website#1262]
### What is the problem?

We have a [Previous Material](https://software-carpentry.org/lessons/previous/) page that has not been updated since 2017.  I recommend removing this page entirely.  @tobyhodges  if you agree I will make the change.  

### Location of problem (optional)

https://software-carpentry.org/lessons/previous/

**Comment by maneesha** [comment]
Along those lines, the main lessons page also refers to checking out our older releases. I would recommend removing that reference as well.  https://software-carpentry.org/lessons/

(edit - typo)

**Comment by maneesha** [comment]
Reminder @tobyhodges

**Comment by maneesha** [comment]
Reminder @tobyhodges

**Comment by tobyhodges** [comment]
One reason that it has taken me a long time to respond here is that I am not completely comfortable with the idea of removing these from the website altogether. I do agree that the page could be removed, and the reference on the main Lessons page. 

But I am left wondering if we should link to the repositories of older versions on the History page? We could add something like "The curriculum used in these workshops is still available on GitHub" with a link to the relevant repository (v4: https://github.com/swcarpentry/v4; v3: https://github.com/swcarpentry/v3) 

What do you think, @martinosorb @quirksahern @vhmcck?

**Comment by quirksahern** [comment]
I’m with @tobyhodges

**Comment by martinosorb** [comment]
I honestly don't think these are very useful. What's the use case? Also, lessons on github are version controlled and one could look at any version.
But if you want to keep them somewhere it's fine, as long as it's clear how old they are.

**Comment by maneesha** [comment]
I'm ok with whatever way consensus leads us.   I will note that we have gotten questions from people who have discovered our old lessons, try to use them, find they don't work (because they are in Python 2 for example) and then contact us for help.  So I'm not sure what the use case would be.  Also, we do not do this for any other lesson program (maybe because SWC is older and has more outdated content?), so this also introduces a level of inconsistency across programs.

**Comment by vhmcck** [comment]
I agree with Martino that Github's version control should suffice.
Why would that be different from keeping repositories of older versions on the History page?

**Comment by tobyhodges** [comment]
> I agree with Martino that Github's version control should suffice.
> Why would that be different from keeping repositories of older versions on the History page?

I think the difference is that some of these old versions of the SWC curriculum are in different repositories from the current lessons i.e. you cannot browse the history of the currently used lessons and find these old versions.

However, those repositories are still available on GitHub, archived and clearly labelled as old versions. So I am ok with removing the page altogether, as seems to be preferred by others.

**Comment by tobyhodges** [comment]
That said, I notice that the https://github.com/swcarpentry/v3 repository is not yet archived. @maneesha please could you adjust the settings on that repo to make it read-only?

**Comment by maneesha** [comment]
I have archived the repo noted above and will be putting in a PR to remove the pages with old content.
