### ISSUE TITLE
Redirect Curriculum Advisors page

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website#1263]
### What is the problem?

The [Curriculum Advisors](https://software-carpentry.org/curriculum-advisors/) page does not have much information on it, and primarily tells people to go to The Carpentries website. I recommend redirecting this page entirely, instead of having this pass through page.  If @tobyhodges agrees, I will make the change.  

### Location of problem (optional)

https://software-carpentry.org/curriculum-advisors/

**Comment by tobyhodges** [comment]
I think this is a great idea 👍
